# Instructions to run:
# cd to folder containing this file
# conda env create
# source activate tdwi

name: tdwi
dependencies:
- python=3.6
- numpy==1.13.1
- jupyter==1.0.0
- matplotlib==2.0.2
- pandas==0.20.3
- scipy==0.19.1
- scikit-learn==0.19.0